# Generated by Django 2.0.3 on 2018-06-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0005_auto_20180602_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonmodel',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='True means the Comparison was deleted'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='True means the Job was deleted'),
            preserve_default=False,
        ),
    ]
