# Generated by Django 2.0.3 on 2018-06-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0007_auto_20180602_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='custom_fields',
            field=models.CharField(default='', help_text="Custom test fields json: {'version': '12.3'}", max_length=1024),
            preserve_default=False,
        ),
    ]
