# Generated by Django 2.0.3 on 2018-06-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0008_testmodel_custom_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='custom_fields',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='attibs',
            field=models.CharField(default='', help_text="Custom test attributes json: {'version': '12.3'}", max_length=1024),
            preserve_default=False,
        ),
    ]
