# Generated by Django 2.0.3 on 2018-06-24 08:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0010_auto_20180602_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='HwFarmNodeLockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='My product perf job #123', max_length=128)),
                ('owner', models.CharField(blank=True, help_text='Jenkins', max_length=64)),
                ('color_rgb', models.CharField(blank=True, help_text='003399', max_length=6)),
                ('begin', models.DateTimeField(default=django.utils.timezone.now, help_text='2018-07-01 12:21:10')),
                ('end', models.DateTimeField(blank=True, help_text='2018-07-01 18:03:45', null=True)),
                ('manual', models.BooleanField(default=False, help_text='True means it was manually locked')),
                ('deleted', models.BooleanField(default=False, help_text='Lock deleted')),
                ('planned_dur_hrs', models.DurationField(default=24, help_text='Planned lock duration (hours)')),
            ],
            options={
                'verbose_name': 'Hw Node Lock',
                'verbose_name_plural': 'Hw Node Locks',
            },
        ),
        migrations.CreateModel(
            name='HwFarmNodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='s1', max_length=64)),
                ('hostname', models.CharField(help_text='s1.perfteam.example.com', max_length=256)),
                ('hidden', models.BooleanField(default=False, help_text='Set to True to hide from the nodes list')),
                ('order', models.IntegerField(help_text='Node order on the dashboard')),
                ('ssh_user', models.CharField(blank=True, help_text='user', max_length=64)),
                ('ssh_passwd', models.CharField(blank=True, help_text='passwd', max_length=64)),
                ('ipmi_ip', models.CharField(blank=True, help_text='10.0.0.1', max_length=64)),
                ('ipmi_user', models.CharField(blank=True, help_text='user', max_length=64)),
                ('ipmi_passwd', models.CharField(blank=True, help_text='passwd', max_length=64)),
                ('icon_url', models.CharField(blank=True, help_text='HW node icon URL', max_length=512)),
                ('dashboard', models.CharField(blank=True, help_text='Node dashboard link (e.g. Grafana)', max_length=512)),
                ('details_url', models.CharField(blank=True, help_text='Node details URL', max_length=512)),
                ('notes', models.CharField(blank=True, help_text='HW node notes', max_length=512)),
                ('description', models.CharField(blank=True, help_text='HW node description', max_length=512)),
                ('inv_id', models.CharField(blank=True, help_text='Inventory ID', max_length=64)),
                ('phys_location', models.CharField(blank=True, help_text='4-2-1-15', max_length=128)),
                ('vendor', models.CharField(blank=True, help_text='HP', max_length=64)),
                ('model', models.CharField(blank=True, help_text='Proliant DL380', max_length=128)),
                ('os', models.CharField(blank=True, help_text='ESXi', max_length=128)),
                ('cpus_count', models.IntegerField(blank=True, help_text='16')),
                ('ram_gb', models.FloatField(blank=True, help_text='32')),
                ('network_gbs', models.FloatField(blank=True, help_text='10')),
                ('storage_tb', models.FloatField(blank=True, help_text='3.2')),
                ('cpu_info', models.CharField(blank=True, help_text='16 (2Sx4Cx2T) @ 2.5GHz, Intel E5450 v2', max_length=64)),
                ('ram_info', models.CharField(blank=True, help_text='32G (1333 GHz)', max_length=64)),
                ('network_info', models.CharField(blank=True, help_text='10GBit X710-DA2', max_length=64)),
                ('storage_info', models.CharField(blank=True, help_text='RAID0, 4x SATA 7200rpm', max_length=64)),
                ('cpu_score', models.FloatField(blank=True, help_text='1.01')),
                ('ram_score', models.FloatField(blank=True, help_text='1.85')),
                ('disk_score', models.FloatField(blank=True, help_text='0.92')),
                ('network_score', models.FloatField(blank=True, help_text='1.21')),
                ('storage_flush_per_sec', models.IntegerField(blank=True, help_text='20124')),
                ('locked_by', models.ForeignKey(blank=True, help_text='Host is locked by given lock', null=True, on_delete=django.db.models.deletion.CASCADE, to='perftracker.HwFarmNodeLockModel')),
                ('projects', models.ManyToManyField(help_text='Project', related_name='hw_node_projects', to='perftracker.ProjectModel')),
            ],
            options={
                'verbose_name': 'Hw Node',
                'verbose_name_plural': 'Hw Nodes',
            },
        ),
    ]
