# Generated by Django 2.0.3 on 2018-06-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0011_hwfarmnodelockmodel_hwfarmnodemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwfarmnodemodel',
            name='ip',
            field=models.CharField(blank=True, help_text='10.0.0.1', max_length=64),
        ),
        migrations.AddField(
            model_name='hwfarmnodemodel',
            name='numa_nodes',
            field=models.IntegerField(blank=True, default=0, help_text='2'),
            preserve_default=False,
        ),
    ]
