# Generated by Django 2.0.3 on 2018-06-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0012_auto_20180624_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwfarmnodemodel',
            name='description',
            field=models.TextField(blank=True, help_text='HW node description'),
        ),
    ]
