# Generated by Django 2.0.3 on 2018-06-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0013_auto_20180624_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwfarmnodemodel',
            name='cpus_count',
            field=models.IntegerField(blank=True, help_text='16', null=True),
        ),
        migrations.AlterField(
            model_name='hwfarmnodemodel',
            name='network_gbs',
            field=models.FloatField(blank=True, help_text='10', null=True),
        ),
        migrations.AlterField(
            model_name='hwfarmnodemodel',
            name='ram_gb',
            field=models.FloatField(blank=True, help_text='32', null=True),
        ),
        migrations.AlterField(
            model_name='hwfarmnodemodel',
            name='storage_tb',
            field=models.FloatField(blank=True, help_text='3.2', null=True),
        ),
    ]
