# Generated by Django 2.0.3 on 2018-06-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0014_auto_20180624_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwfarmnodemodel',
            name='cpu_score',
            field=models.FloatField(blank=True, help_text='1.01', null=True),
        ),
        migrations.AlterField(
            model_name='hwfarmnodemodel',
            name='disk_score',
            field=models.FloatField(blank=True, help_text='0.92', null=True),
        ),
        migrations.AlterField(
            model_name='hwfarmnodemodel',
            name='network_score',
            field=models.FloatField(blank=True, help_text='1.21', null=True),
        ),
        migrations.AlterField(
            model_name='hwfarmnodemodel',
            name='ram_score',
            field=models.FloatField(blank=True, help_text='1.85', null=True),
        ),
    ]
