# Generated by Django 2.0.3 on 2018-06-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0015_auto_20180624_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwfarmnodemodel',
            name='storage_flush_per_sec',
            field=models.IntegerField(blank=True, help_text='20124', null=True),
        ),
    ]
