# Generated by Django 2.0.3 on 2018-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0016_auto_20180624_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwfarmnodemodel',
            name='numa_nodes',
            field=models.IntegerField(blank=True, help_text='2', null=True),
        ),
        migrations.AlterField(
            model_name='hwfarmnodemodel',
            name='order',
            field=models.IntegerField(blank=True, default=10, help_text='Node order on the dashboard'),
        ),
    ]
