# Generated by Django 2.0.3 on 2018-07-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0020_auto_20180701_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='regression_tag',
            field=models.CharField(blank=True, help_text='MyProduct-2.0 regression', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='suite_name',
            field=models.CharField(blank=True, help_text='Test suite name', max_length=128),
        ),
    ]
