# Generated by Django 2.0.3 on 2018-07-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0021_auto_20180701_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='regressionmodel',
            name='jobs',
            field=models.IntegerField(blank=True, default=0, help_text='Number of jobs in regression'),
            preserve_default=False,
        ),
    ]
