# Generated by Django 2.0.3 on 2018-07-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0022_regressionmodel_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='regression_tag',
            field=models.CharField(blank=True, db_index=True, help_text='MyProduct-2.0 regression', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='regressionmodel',
            name='tag',
            field=models.CharField(db_index=True, help_text='MyProduct-2.0 regression', max_length=512),
        ),
    ]
