# Generated by Django 2.0.3 on 2018-07-18 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0023_auto_20180702_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwfarmnodelockmodel',
            name='hw_node',
            field=models.ForeignKey(default=0, help_text='Host', on_delete=django.db.models.deletion.CASCADE, to='perftracker.HwFarmNodeModel'),
            preserve_default=False,
        ),
    ]
