# Generated by Django 2.0.3 on 2018-07-18 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0024_hwfarmnodelockmodel_hw_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hwfarmnodelockmodel',
            name='hw_node',
        ),
        migrations.AddField(
            model_name='hwfarmnodelockmodel',
            name='hw_nodes',
            field=models.ManyToManyField(help_text='Host', limit_choices_to={'locked_by': None}, to='perftracker.HwFarmNodeModel'),
        ),
        migrations.AlterField(
            model_name='hwfarmnodelockmodel',
            name='begin',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='2018-07-01 12:21:10'),
        ),
        migrations.AlterField(
            model_name='hwfarmnodelockmodel',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Lock deleted'),
        ),
        migrations.AlterField(
            model_name='hwfarmnodelockmodel',
            name='end',
            field=models.DateTimeField(blank=True, db_index=True, help_text='2018-07-01 18:03:45', null=True),
        ),
    ]
