# Generated by Django 2.0.3 on 2018-07-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0026_auto_20180718_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hwfarmnodelockmodel',
            name='color_rgb',
        ),
    ]
