# Generated by Django 2.1.1 on 2018-09-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0028_auto_20180910_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='regression_linked',
            field=models.ForeignKey(blank=True, help_text='Regression this job linked to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regr_linked', to='perftracker.RegressionModel'),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='regression_original',
            field=models.ForeignKey(blank=True, help_text='Original regression of this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regr_original', to='perftracker.RegressionModel'),
        ),
    ]
