# Generated by Django 2.1.1 on 2018-09-14 15:42

from django.db import migrations, models
import django.db.models.deletion


def linkJobToRegression(apps, schema_editor):
    JobModel        = apps.get_model('perftracker', 'JobModel')
    RegressionModel = apps.get_model('perftracker', 'RegressionModel')

    for regression in RegressionModel.objects.all():
        for job in JobModel.objects.filter(regression_tag=regression.tag).all():
            job.regression_original = regression
            job.regression_linked   = regression
            job.save()


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0029_auto_20180914_1542'),
    ]

    operations = [
        migrations.RunPython(
            linkJobToRegression
        ),
    ]
