# Generated by Django 2.1.1 on 2018-09-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0030_perftracker_jobmodel_migration')
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='regression_tag',
        ),
    ]
