# Generated by Django 2.0.3 on 2018-09-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0031_perftracker_jobmodel_migration'),
        ('perftracker', '0028_auto_20180914_0056'),
    ]

    operations = [
    ]
