# Generated by Django 2.0.3 on 2018-09-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0033_artifactlinkmodel_artifactmetamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactmetamodel',
            name='deleted_dt',
            field=models.DateTimeField(blank=True, default=None, help_text='Datetime when artifact was deleted by garbage collector', null=True),
        ),
    ]
