# Generated by Django 2.0.3 on 2018-09-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0035_auto_20180930_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactlinkmodel',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Artifact link is deleted'),
        ),
    ]
