# Generated by Django 2.0.3 on 2018-09-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0037_auto_20181001_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactmetamodel',
            name='compression',
            field=models.BooleanField(default=False, help_text='Decompress on download/view'),
        ),
        migrations.AddField(
            model_name='artifactmetamodel',
            name='inline',
            field=models.BooleanField(default=False, help_text='View document in browser (do not download)'),
        ),
        migrations.AlterField(
            model_name='artifactmetamodel',
            name='mime',
            field=models.CharField(default='', help_text='Artifact file mime type', max_length=32),
        ),
    ]
