# Generated by Django 2.0.3 on 2018-10-01 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0038_auto_20181001_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifactlinkmodel',
            name='artifact_uuid',
        ),
        migrations.AddField(
            model_name='artifactlinkmodel',
            name='artifact',
            field=models.ForeignKey(default=0, help_text='Artifact', on_delete=django.db.models.deletion.CASCADE, to='perftracker.ArtifactMetaModel'),
            preserve_default=False,
        ),
    ]
