# Generated by Django 2.0.3 on 2018-10-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0039_auto_20181002_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonmodel',
            name='job_ids',
            field=models.TextField(default='', help_text="Id's of the jobs (needed for proper jobs ordering)"),
            preserve_default=False,
        ),
    ]
