# Generated by Django 2.0.3 on 2018-10-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0040_comparisonmodel_job_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparisonmodel',
            old_name='jobs',
            new_name='_jobs',
        ),
    ]
