# Generated by Django 2.0.3 on 2018-10-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0041_auto_20181005_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparisonmodel',
            old_name='job_ids',
            new_name='_job_ids',
        ),
    ]
