# Generated by Django 2.0.3 on 2018-10-05 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0042_auto_20181005_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='HwFarmNodeLockTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Lock type name', max_length=128)),
                ('bg_color', models.CharField(help_text='The background color: #003399', max_length=7)),
                ('fg_color', models.CharField(help_text='The foreground color: #ffffff', max_length=7)),
            ],
            options={
                'verbose_name': 'Hw Node Lock Type',
                'verbose_name_plural': 'Hw Node Lock Types',
            },
        ),
        migrations.AddField(
            model_name='hwfarmnodelockmodel',
            name='lock_type',
            field=models.ForeignKey(blank=True, default=None, help_text='Lock type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='perftracker.HwFarmNodeLockTypeModel'),
        ),
    ]
