# Generated by Django 2.0.3 on 2018-10-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0044_hwfarmnodelocktypemodel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwfarmnodemodel',
            name='purpose',
            field=models.CharField(default='', help_text='a test server', max_length=256),
            preserve_default=False,
        ),
    ]
