# Generated by Django 2.0.3 on 2018-12-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0047_auto_20181019_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='envnodemodel',
            name='cpus_topology',
            field=models.CharField(blank=True, help_text='32 (2S x 8C x 2T)', max_length=128, null=True),
        ),
    ]
