# Generated by Django 2.2.5 on 2019-10-14 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0048_envnodemodel_cpus_topology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactlinkmodel',
            name='deleted',
            field=models.BooleanField(blank=True, db_index=True, default=False, help_text='Artifact link is deleted'),
        ),
        migrations.AlterField(
            model_name='artifactmetamodel',
            name='deleted',
            field=models.BooleanField(blank=True, db_index=True, default=False, help_text='Artifact is deleted'),
        ),
        migrations.AlterField(
            model_name='envnodemodel',
            name='job',
            field=models.ForeignKey(help_text='Job', on_delete=django.db.models.deletion.CASCADE, related_name='env_nodes', to='perftracker.JobModel'),
        ),
    ]
