# Generated by Django 2.1.5 on 2019-10-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0050_traindatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='testcases_total',
            field=models.IntegerField(help_text='Total number of test cases in the job', null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='testcases_errors',
            field=models.IntegerField(help_text='Number of test cases with test errors/failures', null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='tests_completed',
            field=models.IntegerField(help_text='Number of tests completed', null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='tests_errors',
            field=models.IntegerField(default=0, help_text='Number of tests with errors (includes failed)', null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='tests_failed',
            field=models.IntegerField(default=0, help_text='Number of failed tests', null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='tests_warnings',
            field=models.IntegerField(default=0, help_text='Number of tests with warnings', null=True),
        ),
    ]
