# Generated by Django 2.2.5 on 2019-10-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0053_jobmodel_counters_not_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='traindatamodel',
            name='job_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='traindatamodel',
            name='section_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
