# Generated by Django 2.2.5 on 2019-10-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0054_traindatamodel_add_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='traindatamodel',
            name='chart_is_ok',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=None),
        ),
        migrations.AlterField(
            model_name='traindatamodel',
            name='anomaly',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')], null=True),
        ),
        migrations.AlterField(
            model_name='traindatamodel',
            name='fails',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='traindatamodel',
            name='function_type',
            field=models.IntegerField(choices=[(0, 'Not specified'), (1, 'Constant'), (2, 'Linear'), (3, 'Logarithm'), (4, 'Square or exp'), (5, 'Hyperbola')], null=True),
        ),
        migrations.AlterField(
            model_name='traindatamodel',
            name='job_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='traindatamodel',
            name='less_better',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='traindatamodel',
            name='oscillation',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')], null=True),
        ),
        migrations.AlterField(
            model_name='traindatamodel',
            name='outliers',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, 'Many')], null=True),
        ),
        migrations.AlterField(
            model_name='traindatamodel',
            name='section_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
