# Generated by Django 2.2.5 on 2019-11-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0055_traindatamodel_modified_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traindatamodel',
            old_name='oscillation',
            new_name='deviation',
        ),
    ]
