# Generated by Django 2.2.3 on 2020-01-30 09:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('perftracker', '0056_traindatamodel_rename_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='unique link number')),
                ('plots_identifiers', models.CharField(help_text='Charts ID', max_length=10000)),
                ('search_pattern', models.CharField(blank=True, help_text='search info in navigation bar', max_length=100)),
                ('comparison', models.ForeignKey(help_text='Comparison id', on_delete=django.db.models.deletion.CASCADE, to='perftracker.ComparisonModel')),
                ('project', models.ForeignKey(help_text='Comparison project', on_delete=django.db.models.deletion.CASCADE, to='perftracker.ProjectModel')),
            ],
            options={
                'verbose_name': 'Array of Identifiers for Link ',
            },
        ),
    ]
